--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 20 2018 14:47
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'PersonAddressType'   
--
DROP TABLE PersonAddressType
GO
--
-- Drop Table    : 'PersonAddress'   
--
DROP TABLE PersonAddress
GO
--
-- Drop Table    : 'AddressType'   
--
DROP TABLE AddressType
GO
--
-- Drop Table    : 'Address'   
--
DROP TABLE Address
GO
--
-- Drop Table    : 'City'   
--
DROP TABLE City
GO
--
-- Drop Table    : 'ZipCode'   
--
DROP TABLE ZipCode
GO
--
-- Drop Table    : 'TelephoneNumber'   
--
DROP TABLE TelephoneNumber
GO
--
-- Drop Table    : 'CountryCode'   
--
DROP TABLE CountryCode
GO
--
-- Drop Table    : 'TelephoneCompany'   
--
DROP TABLE TelephoneCompany
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
