--
-- Target: Microsoft SQL Server
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 20 2018 14:47
-- Script Generated by Database Design Studio 2.21.3
--


--
-- Create Table    : 'Person'
-- PersonId        :
-- FirstName       :
-- MiddleName      :
-- LastName        :
-- Context         :
-- Email           :
--
CREATE TABLE Person (
    PersonId       INT NOT NULL UNIQUE,
    FirstName      VARCHAR NOT NULL,
    MiddleName     VARCHAR NULL,
    LastName       VARCHAR NOT NULL,
    Context        VARCHAR NOT NULL,
    Email          VARCHAR NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonId))
GO

--
-- Create Table    : 'TelephoneCompany'
-- TelephoneCompanyId :
-- Company         :
--
CREATE TABLE TelephoneCompany (
    TelephoneCompanyId INT NOT NULL UNIQUE,
    Company        VARCHAR NOT NULL,
CONSTRAINT pk_TelephoneCompany PRIMARY KEY CLUSTERED (TelephoneCompanyId))
GO

--
-- Create Table    : 'CountryCode'
-- CountryCodeId   :
-- Code            :
--
CREATE TABLE CountryCode (
    CountryCodeId  INT NOT NULL UNIQUE,
    Code           VARCHAR NOT NULL,
CONSTRAINT pk_CountryCode PRIMARY KEY CLUSTERED (CountryCodeId))
GO

--
-- Create Table    : 'TelephoneNumber'
-- TelephoneNumberId :
-- Number          : Number is a SQL keyworld
-- Use             : Use is a SQL Keyword
-- PersonId        :  (references Person.PersonId)
-- TelephoneCompanyId :  (references TelephoneCompany.TelephoneCompanyId)
--
CREATE TABLE TelephoneNumber (
    TelephoneNumberId INT NOT NULL UNIQUE,
    Number         VARCHAR NOT NULL,
    Usee            VARCHAR NOT NULL,
    PersonId       INT NULL,
    TelephoneCompanyId INT NOT NULL,
CONSTRAINT pk_TelephoneNumber PRIMARY KEY CLUSTERED (TelephoneNumberId),
CONSTRAINT fk_TelephoneNumber FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON UPDATE CASCADE,
CONSTRAINT fk_TelephoneNumber2 FOREIGN KEY (TelephoneCompanyId)
    REFERENCES TelephoneCompany (TelephoneCompanyId)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'ZipCode'
-- ZipCodeId       :
-- Zip             :
-- CountryCodeId   :  (references CountryCode.CountryCodeId)
--
CREATE TABLE ZipCode (
    ZipCodeId      INT NOT NULL UNIQUE,
    Zip            VARCHAR NOT NULL,
    CountryCodeId  INT NOT NULL,
CONSTRAINT pk_ZipCode PRIMARY KEY CLUSTERED (ZipCodeId),
CONSTRAINT fk_ZipCode FOREIGN KEY (CountryCodeId)
    REFERENCES CountryCode (CountryCodeId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'City'
-- CityId          :
-- Postnummer      :
-- Name            :
-- ZipCodeId       :  (references ZipCode.ZipCodeId)
--
CREATE TABLE City (
    CityId         INT NOT NULL UNIQUE,
    Postnummer     VARCHAR NOT NULL,
    Name           VARCHAR NOT NULL,
    ZipCodeId      INT NOT NULL,
CONSTRAINT pk_City PRIMARY KEY CLUSTERED (CityId),
CONSTRAINT fk_City FOREIGN KEY (ZipCodeId)
    REFERENCES ZipCode (ZipCodeId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Address'
-- AddressId       :
-- StreetName      :
-- HouseNumber     :
-- CityId          :  (references City.CityId)
--
CREATE TABLE Address (
    AddressId      INT NOT NULL UNIQUE,
    StreetName     VARCHAR NOT NULL,
    HouseNumber    VARCHAR NOT NULL,
    CityId         INT NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (AddressId),
CONSTRAINT fk_Address FOREIGN KEY (CityId)
    REFERENCES City (CityId)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AddressType'
-- AdresseTypeID   :
-- Type            :
-- AddressId       :  (references Address.AddressId)
--
CREATE TABLE AddressType (
    AdresseTypeID  INT NOT NULL UNIQUE,
    Type           VARCHAR NOT NULL,
    AddressId      INT NULL,
CONSTRAINT pk_AddressType PRIMARY KEY CLUSTERED (AdresseTypeID),
CONSTRAINT fk_AddressType FOREIGN KEY (AddressId)
    REFERENCES Address (AddressId)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonAddress'
-- PersonId        :  (references Person.PersonId)
-- AddressId       :  (references Address.AddressId)
--
CREATE TABLE PersonAddress (
    PersonId       INT NOT NULL,
    AddressId      INT NOT NULL,
CONSTRAINT pk_PersonAddress PRIMARY KEY CLUSTERED (PersonId,AddressId),
CONSTRAINT fk_PersonAddress FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonAddress2 FOREIGN KEY (AddressId)
    REFERENCES Address (AddressId)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PersonAddressType'
-- PersonId        :  (references Person.PersonId)
-- AdresseTypeID   :  (references AddressType.AdresseTypeID)
--
CREATE TABLE PersonAddressType (
    PersonId       INT NOT NULL,
    AdresseTypeID  INT NOT NULL,
CONSTRAINT pk_PersonAddressType PRIMARY KEY CLUSTERED (PersonId,AdresseTypeID),
CONSTRAINT fk_PersonAddressType FOREIGN KEY (PersonId)
    REFERENCES Person (PersonId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_PersonAddressType2 FOREIGN KEY (AdresseTypeID)
    REFERENCES AddressType (AdresseTypeID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Person TO public
GO
GRANT ALL ON TelephoneCompany TO public
GO
GRANT ALL ON CountryCode TO public
GO
GRANT ALL ON TelephoneNumber TO public
GO
GRANT ALL ON ZipCode TO public
GO
GRANT ALL ON City TO public
GO
GRANT ALL ON Address TO public
GO
GRANT ALL ON AddressType TO public
GO
GRANT ALL ON PersonAddress TO public
GO
GRANT ALL ON PersonAddressType TO public
GO

