//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAB2_2.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelephoneNumber
    {
        public int TelephoneNumberId { get; set; }
        public string Number { get; set; }
        public string Usere { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int TelephoneCompanyId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual TelephoneCompany TelephoneCompany { get; set; }
    }
}
